# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Changes made to support docker as a provider.
# 
Vagrant.require_version '>= 1.4.3'
VAGRANTFILE_API_VERSION = '2'.freeze

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.provider "docker" do |d|
	    d.image = "nishidayuya/docker-vagrant-ubuntu:xenial"
	    d.has_ssh = true
	    d.ports = ["8088:8088","8082:8082","9083:9083","4040:4040","8888:8888", "9200:9200", "5601:5601", "15672:15672", "5555:5555"]
    end
    config.vm.provider "virtualbox" do |v, override|
	    override.vm.box = "ubuntu/xenial64"
	    v.gui = false
	    v.name = "learnairflow"
            v.customize ['modifyvm', :id, '--memory', '8192']
    end
    config.vm.network "forwarded_port", guest: 8082, host: 8082
    config.vm.network "forwarded_port", guest: 8088, host: 8088
    config.vm.network "forwarded_port", guest: 9083, host: 9083
    config.vm.network "forwarded_port", guest: 4040, host: 4040
    config.vm.network "forwarded_port", guest: 18888, host: 18888
    config.vm.network "forwarded_port", guest: 9200, host: 9200
    config.vm.network "forwarded_port", guest: 5601, host: 5601
    config.vm.network "forwarded_port", guest: 15672, host: 15672
    config.vm.network "forwarded_port", guest: 5555, host: 5555
    config.vm.define "learnairflow" do |node|
        node.vm.network :private_network, ip: '10.211.55.101'
        node.vm.hostname = 'learnairflow'
        node.vm.provision :shell, path: 'scripts/setup-ubuntu.sh'
        node.vm.provision :shell, path: 'scripts/setup-java.sh'
        node.vm.provision :shell, path: 'scripts/setup-hadoop.sh'
        node.vm.provision :shell, path: 'scripts/setup-hive.sh'
        node.vm.provision :shell, path: 'scripts/setup-spark.sh'
        node.vm.provision :shell, path: 'scripts/setup-es.sh'
        node.vm.provision :shell, path: 'scripts/setup-kibana.sh'
        node.vm.provision :shell, path: 'scripts/setup-rabbitmq.sh'
        node.vm.provision :shell, path: 'scripts/setup-materials.sh'
        node.vm.provision :shell, path: 'scripts/setup-mysql.sh'
        node.vm.provision :shell, path: 'scripts/setup-virtualenv.sh'
        node.vm.provision :shell, path: 'scripts/setup-sqlite3.sh'
	# Optional components - uncomment to include
        node.vm.provision :shell, path: 'scripts/finalize-ubuntu.sh'
        node.vm.provision :shell, path: 'scripts/bootstrap.sh', run: 'always'
    end
end
